# base{{{
x-base: &base
  restart: "no"
  build:
    args:
      EXEC_UID: "${EXEC_UID:-1000}"
      EXEC_USER: "${EXEC_USER:-ansible}"
      EXEC_GID: "${EXEC_GID:-1000}"
      EXEC_GROUP: "${EXEC_GROUP:-ansible}"
      EXEC_USER_PASSWD: "${EXEC_USER_PASSWD:-ansible}"
  init: true
  tty: true
  stdin_open: true
  privileged: true
  volumes:
    - /etc/localtime:/etc/localtime:ro
  logging: &logging
    driver: json-file
    options:
      max-size: "100m"
      max-file: "10"
# }}}

services:
  &centos7 centos7-systemd: # {{{
    << : *base
    build:
      context: ./centos7
    image: nakahiro386/centos7-systemd:latest
    container_name: *centos7
    hostname: *centos7
    ports:
      - "${CENTOS7_SSH_PORT:-2222}:22"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
  #}}}

  &oraclelinux7 oraclelinux7-systemd: # {{{
    << : *base
    build:
      context: ./oraclelinux7
    image: nakahiro386/oraclelinux7-systemd:latest
    container_name: *oraclelinux7
    hostname: *oraclelinux7
    ports:
      - "${ORACLELINUX7_SSH_PORT:-2223}:22"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
  #}}}

  &oraclelinux8 oraclelinux8-systemd: # {{{
    << : *base
    build:
      context: ./oraclelinux8
    image: nakahiro386/oraclelinux8-systemd:latest
    container_name: *oraclelinux8
    hostname: *oraclelinux8
    cgroup: host
    init: false
    ports:
      - "${ORACLELINUX8_SSH_PORT:-2224}:22"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /run
  #}}}

  &ubuntu2204 ubuntu2204-systemd: # {{{
    << : *base
    build:
      context: ./ubuntu2204
    image: nakahiro386/ubuntu2204-systemd:latest
    container_name: *ubuntu2204
    hostname: *ubuntu2204
    cgroup: host
    init: false
    ports:
      - "${UBUNTU2204_SSH_PORT:-2225}:22"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /run
  #}}}

  &ubuntu2404 ubuntu2404-systemd: # {{{
    << : *base
    build:
      context: ./ubuntu2404
    image: nakahiro386/ubuntu2404-systemd:latest
    container_name: *ubuntu2404
    hostname: *ubuntu2404
    cgroup: host
    init: false
    ports:
      - "${UBUNTU2404_SSH_PORT:-2226}:22"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /run
  #}}}

# vim:set filetype=docker-compose expandtab shiftwidth=2 tabstop=2 foldmethod=marker:
